--
-- Script was generated by Devart dbForge Studio for MySQL, Version 2025.2.37.0
-- Product home page: https://www.devart.com/dbforge/mysql/studio
-- Script date 20-01-2026 11:42:14
-- Server version: 10.4.32
--

SET NAMES 'utf8';

INSERT INTO market_analysis_db.analysis_items(item_id, report_id, entity_name, event_details, layman_explanation) VALUES
(2, 2, 'The Headline', 'Omaxe invests ?500 Cr in Ludhiana', 'A big real estate company (Omaxe) is spending ?500 Crore to build a massive project in Ludhiana, Punjab. This shows they are very confident that people in Punjab will buy expensive homes and shop at premium places.');
INSERT INTO market_analysis_db.analysis_items(item_id, report_id, entity_name, event_details, layman_explanation) VALUES
(3, 2, 'The Project', '"Omaxe Chowk" (Mixed-Use)', 'They are not just building houses or just a mall. They are mixing it up: Retail Shops + Luxury Homes + Entertainment all in one place (5.25 acres). Think of it as a "mini-city" inside Ludhiana where you can live, shop, and eat without leaving the area.');
INSERT INTO market_analysis_db.analysis_items(item_id, report_id, entity_name, event_details, layman_explanation) VALUES
(4, 2, 'The Location', 'Ghumar Mandi, Ludhiana', 'They chose a very busy, popular market area (Ghumar Mandi). The land actually belongs to the Railways (RLDA), and Omaxe won a bid to develop it. This transforms a busy, old area into a modern "high-street" destination.');
INSERT INTO market_analysis_db.analysis_items(item_id, report_id, entity_name, event_details, layman_explanation) VALUES
(5, 2, 'Timeline', 'Completion by June 2030', 'This is a long-term project. It will take about 4-5 years to finish. For investors, this means the profits won''t come immediately, but it adds long-term value to the company.');
INSERT INTO market_analysis_db.analysis_items(item_id, report_id, entity_name, event_details, layman_explanation) VALUES
(6, 2, 'Stock Impact', 'Shares up ~7%', 'The stock market loved this news. When a company announces a clear plan to spend money and grow, investors get excited, pushing the share price up.');
INSERT INTO market_analysis_db.analysis_items(item_id, report_id, entity_name, event_details, layman_explanation) VALUES
(7, 3, 'Value Time Over Money', 'Don''t just work for hourly wages.\n\n\nPoor people sell their time (work = pay). Wealthy people build things (systems) that keep working even when they take a break.', 'If you only earn when you work, you will work until you die. You need "machines" (assets) that earn for you.');
INSERT INTO market_analysis_db.analysis_items(item_id, report_id, entity_name, event_details, layman_explanation) VALUES
(8, 3, 'Assets > Active Income', 'Don''t rely on just a salary.\n\n\nA salary stops the day you stop working. An "asset" (like a rental shop or dividend stock) keeps paying you regardless of your health or mood.', 'Your salary is risky because it depends entirely on your presence. Assets provide true safety.');
INSERT INTO market_analysis_db.analysis_items(item_id, report_id, entity_name, event_details, layman_explanation) VALUES
(9, 3, 'The Power of "Boring"', 'Flashy isn''t always profitable.\n\n\nYou don''t need a high-tech startup. Simple, boring businesses (like being a distributor or connector) often make more steady money than risky, trendy ventures.', 'Boring businesses usually have loyal customers and steady cash flow, surviving bad times better than "hyped" trends.');
INSERT INTO market_analysis_db.analysis_items(item_id, report_id, entity_name, event_details, layman_explanation) VALUES
(10, 3, 'Scale > Perfection', 'Don''t wait for the perfect idea.\n\n\nA "good enough" plan that reaches 1,000 people is better than a "perfect" plan that never leaves your notebook.', 'Waiting for perfection kills growth. Wealthy people launch "okay" ideas and fix them along the way.');
INSERT INTO market_analysis_db.analysis_items(item_id, report_id, entity_name, event_details, layman_explanation) VALUES
(11, 3, 'Middleman Strategy', 'Be the bridge.\n\n\nYou don''t have to manufacture the product or be the final seller. Being the "connector" in the middle (distributor) is a quiet, powerful way to make money.', 'Middlemen often profit from high volume and repeat business without the headaches of manufacturing.');
INSERT INTO market_analysis_db.analysis_items(item_id, report_id, entity_name, event_details, layman_explanation) VALUES
(12, 4, 'The Headline', 'Govt asks apps to drop "10-min delivery"', 'The Indian government has told companies like Blinkit, Zepto, and Zomato to stop promising deliveries in 10 minutes. They feel this promise makes driving dangerous for the delivery boys.');
INSERT INTO market_analysis_db.analysis_items(item_id, report_id, entity_name, event_details, layman_explanation) VALUES
(13, 4, 'The Trigger', 'Nationwide Strike & Safety Concerns', 'Delivery riders recently went on strike (Dec 31, 2025) because the pressure to deliver so fast was causing accidents and stress. The Labour Ministry held meetings with the companies after this.');
INSERT INTO market_analysis_db.analysis_items(item_id, report_id, entity_name, event_details, layman_explanation) VALUES
(14, 4, 'Companies Involved', 'Blinkit, Zepto, Swiggy Instamart', 'These are the apps you use for quick grocery needs. Blinkit has reportedly already removed the "10-minute" branding, and others are expected to follow.');
INSERT INTO market_analysis_db.analysis_items(item_id, report_id, entity_name, event_details, layman_explanation) VALUES
(15, 4, 'Worker Reality', 'High Pressure, Low Pay', 'Riders like Mobin Alam describe working 12+ hours for just ?20,000/month. Missing a deadline often means penalties or fewer orders, forcing them to drive rashly.');
INSERT INTO market_analysis_db.analysis_items(item_id, report_id, entity_name, event_details, layman_explanation) VALUES
(16, 4, 'The Outcome', 'Safety over Speed', 'You will still get your groceries quickly (because local dark stores are nearby), but the apps won''t guarantee or advertise a specific 10-minute countdown anymore to reduce pressure on the rider.');
INSERT INTO market_analysis_db.analysis_items(item_id, report_id, entity_name, event_details, layman_explanation) VALUES
(17, 5, 'The Headline', 'Profit Hits NT$505.7 Billion', 'TSMC made a pure profit of roughly ?1.3 Lakh Crore (converted) in just 3 months. This is a new all-time record, beating what experts predicted.');
INSERT INTO market_analysis_db.analysis_items(item_id, report_id, entity_name, event_details, layman_explanation) VALUES
(18, 5, 'The Driver', 'Insane AI Demand', 'Companies like Nvidia and Apple are buying every advanced chip TSMC can make. AI needs super-powerful chips, and TSMC is the only one who can make them reliably.');
INSERT INTO market_analysis_db.analysis_items(item_id, report_id, entity_name, event_details, layman_explanation) VALUES
(19, 5, 'Revenue', 'NT$1.05 Trillion', 'For the first time, they sold over 1 Trillion (Taiwan Dollars) worth of chips in a single quarter. That’s a 20% jump compared to last year.');
INSERT INTO market_analysis_db.analysis_items(item_id, report_id, entity_name, event_details, layman_explanation) VALUES
(20, 5, 'Tech Leadership', '3nm & 5nm Chips', '63% of their money came from their most advanced chips (3nm and 5nm). Think of these as the "Ferraris" of chips—expensive, fast, and in high demand.');
INSERT INTO market_analysis_db.analysis_items(item_id, report_id, entity_name, event_details, layman_explanation) VALUES
(21, 5, 'Margins', '62.3% Gross Margin', 'For every $100 they earn, they keep $62.3 as gross profit. This is extremely high for a factory business, showing they have no real competition and can charge premium prices.');
INSERT INTO market_analysis_db.analysis_items(item_id, report_id, entity_name, event_details, layman_explanation) VALUES
(22, 5, 'Future Outlook', 'Growth to Continue', 'Even though things might slow down slightly in early 2026, the long-term demand for AI is expected to keep them growing. They are building more factories to keep up.');
INSERT INTO market_analysis_db.analysis_items(item_id, report_id, entity_name, event_details, layman_explanation) VALUES
(23, 6, 'The Headline', 'Silver Holds Above $90', 'Silver has historically been cheaper than gold, but it just crossed a massive milestone of $90 per ounce. It is currently outperforming gold.');
INSERT INTO market_analysis_db.analysis_items(item_id, report_id, entity_name, event_details, layman_explanation) VALUES
(24, 6, 'The Drivers', 'AI, Solar & Scarcity', 'Silver isn''t just for jewelry anymore. It is essential for Solar Panels, Electric Vehicles (EVs), and AI hardware. The world is building these fast, and mines can''t dig up silver fast enough to keep up (Annual deficit of ~200 million ounces).');
INSERT INTO market_analysis_db.analysis_items(item_id, report_id, entity_name, event_details, layman_explanation) VALUES
(25, 6, 'Stock Impact', 'Miners are Rallying', 'Since the price of the product (silver) is up, the companies selling it are making huge profits. Stocks like Hindustan Zinc (+6%), Newmont, and Barrick Gold are surging.');
INSERT INTO market_analysis_db.analysis_items(item_id, report_id, entity_name, event_details, layman_explanation) VALUES
(26, 6, 'Future Outlook', 'Target: $100 by March', 'Banks like Citi are predicting silver could hit $100 by March 2026. This suggests the rally might have more room to grow.');
INSERT INTO market_analysis_db.analysis_items(item_id, report_id, entity_name, event_details, layman_explanation) VALUES
(27, 6, 'Risk Factor', '"Disconnect" Warning', 'Some experts warn that if the general stock market falls (due to economic fear), mining stocks might fall too, even if silver prices stay high. Be careful of "fake breakouts".');