--
-- Script was generated by Devart dbForge Studio for MySQL, Version 2025.2.37.0
-- Product home page: https://www.devart.com/dbforge/mysql/studio
-- Script date 21-01-2026 15:48:15
-- Server version: 10.4.32
--

SET NAMES 'utf8';

INSERT INTO market_analysis_db.analysis_reports(report_id, report_date, source_url, title, overall_strategy, created_at) VALUES
(2, '2026-01-14', NULL, 'Omaxe invests ?500 Cr in Ludhiana', 'Omaxe is developing a 5.25-acre project named "Omaxe Chowk" in Ludhiana with an investment of ?500 Crore. It is a PPP project with the Rail Land Development Authority (RLDA). The project combines luxury housing and high-street retail and is expected to be finished by June 2030. The stock jumped 7% on this news.', '2026-01-14 15:38:49');
INSERT INTO market_analysis_db.analysis_reports(report_id, report_date, source_url, title, overall_strategy, created_at) VALUES
(3, '2026-01-14', NULL, '"Wealth building mindset explained by CA" (featuring CA Nitin Kaushik)', 'The Core Idea: Real wealth isn''t about flashy cars or huge salaries. It is about building "boring" systems that make money while you sleep, valuing time over money, and scaling simple ideas instead of waiting for perfect ones.', '2026-01-15 08:12:39');
INSERT INTO market_analysis_db.analysis_reports(report_id, report_date, source_url, title, overall_strategy, created_at) VALUES
(4, '2026-01-15', NULL, 'India asks e-commerce apps to stop ''10-minute'' delivery service', 'The Indian government has directed quick-commerce platforms (Blinkit, Zepto, Zomato) to remove the "10-minute delivery" promise from their marketing. This decision follows a nationwide strike by delivery workers on Dec 31, 2025, highlighting safety risks and pressure. While apps will still deliver quickly due to nearby dark stores, the explicit deadline pressure is being removed to improve road safety and worker conditions.', '2026-01-15 08:25:58');
INSERT INTO market_analysis_db.analysis_reports(report_id, report_date, source_url, title, overall_strategy, created_at) VALUES
(5, '2026-01-15', NULL, 'TSMC delivers another record quarter as profit jumps 35% fueled by robust AI chip demand', 'TSMC reported a record Q4 2025 net profit of NT$505.7 billion, beating analyst estimates. Revenue crossed NT$1 trillion for the first time, driven by surging demand for AI chips from Nvidia and Apple. Gross margins remained high at 62.3%, highlighting their dominance in advanced (3nm/5nm) chip manufacturing.', '2026-01-15 15:14:07');
INSERT INTO market_analysis_db.analysis_reports(report_id, report_date, source_url, title, overall_strategy, created_at) VALUES
(6, '2026-01-15', NULL, 'Silver Holds Above $90', 'Silver prices have broken the $90/oz milestone, driven by severe supply shortages and high industrial demand from the AI and Green Energy sectors. Major banks like Citi are now targeting $100 by March. Mining stocks like Hindustan Zinc and Newmont are rallying in response to these record prices.', '2026-01-15 16:06:33');